// Stable machine-readable codes that the frontend can branch on.
// (Prefer constants over string literals sprinkled throughout.)

// Auth / generic
pub const UNAUTHORIZED: &str = "UNAUTHORIZED";
pub const FORBIDDEN: &str = "FORBIDDEN";
pub const NOT_FOUND: &str = "NOT_FOUND";
pub const CONFLICT: &str = "CONFLICT";
pub const INTERNAL: &str = "INTERNAL";

// Validation (auth)
pub const VALIDATION_EMAIL_INVALID: &str = "VALIDATION_EMAIL_INVALID";
pub const VALIDATION_USERNAME_INVALID: &str = "VALIDATION_USERNAME_INVALID";
pub const VALIDATION_PASSWORD_TOO_SHORT: &str = "VALIDATION_PASSWORD_TOO_SHORT";
pub const VALIDATION_LOGIN_MISSING: &str = "VALIDATION_LOGIN_MISSING";

// Validation (posts)
pub const VALIDATION_TITLE_REQUIRED: &str = "VALIDATION_TITLE_REQUIRED";
pub const VALIDATION_BODY_REQUIRED: &str = "VALIDATION_BODY_REQUIRED";
pub const VALIDATION_NOTHING_TO_UPDATE: &str = "VALIDATION_NOTHING_TO_UPDATE";
pub const VALIDATION_TITLE_EMPTY: &str = "VALIDATION_TITLE_EMPTY";
pub const VALIDATION_BODY_EMPTY: &str = "VALIDATION_BODY_EMPTY";
pub const VALIDATION_POST_NOT_FOUND: &str = "VALIDATION_POST_NOT_FOUND";

// Validation (comments)
pub const VALIDATION_PARENT_NOT_FOUND: &str = "VALIDATION_PARENT_NOT_FOUND";
pub const VALIDATION_PARENT_NOT_IN_POST: &str = "VALIDATION_PARENT_NOT_IN_POST";
pub const VALIDATION_COMMENT_NOT_FOUND: &str = "VALIDATION_COMMENT_NOT_FOUND";

// Validation (tags)
pub const VALIDATION_TAG_NAME_INVALID: &str = "VALIDATION_TAG_NAME_INVALID";
pub const VALIDATION_TAG_NOT_FOUND: &str = "VALIDATION_TAG_NOT_FOUND";
pub const VALIDATION_TAG_ALREADY_ATTACHED: &str = "VALIDATION_TAG_ALREADY_ATTACHED";

// Validation (reports)
pub const REPORT_ENTITY_TYPE_INVALID: &str = "VALIDATION_REPORT_ENTITY_TYPE_INVALID"; // not in {"post","comment","user"}
pub const REPORT_REASON_EMPTY: &str = "VALIDATION_REPORT_REASON_EMPTY";
pub const REPORT_REASON_TOO_LONG: &str = "VALIDATION_REPORT_REASON_TOO_LONG";
pub const REPORT_STATUS_INVALID: &str = "VALIDATION_REPORT_STATUS_INVALID"; // not in {"open","reviewed","dismissed","actioned"}
pub const REPORT_TARGET_NOT_FOUND: &str = "VALIDATION_REPORT_TARGET_NOT_FOUND"; // reported object doesn't exist

// Validation (avatars)
pub const AVATAR_BAD_MULTIPART: &str = "VALIDATION_AVATAR_BAD_MULTIPART";
pub const AVATAR_MISSING_FILE: &str = "VALIDATION_AVATAR_MISSING_FILE";
pub const AVATAR_TOO_LARGE: &str = "VALIDATION_AVATAR_TOO_LARGE";
pub const AVATAR_INVALID_FORMAT: &str = "VALIDATION_AVATAR_INVALID_FORMAT";
pub const AVATAR_DECODE_FAILED: &str = "VALIDATION_AVATAR_DECODE_FAILED";

// Validation (users - profile updates)
pub const VALIDATION_USER_DOB_INVALID: &str = "VALIDATION_USER_DOB_INVALID";
pub const VALIDATION_USER_BIO_TOO_LONG: &str = "VALIDATION_USER_BIO_TOO_LONG";

// Notifications
pub const VALIDATION_INVALIDE_PAGE: &str = "VALIDATION_INVALID_PAGE";
pub const VALIDATION_INVALIDE_LIMIT: &str = "VALIDATION_INVALID_LIMIT";
pub const VALIDATION_EMPTY_IDS: &str = "VALIDATION_EMPTY_IDS";
pub const VALIDATION_TOO_MANY_IDS: &str = "VALIDATION_TOO_MANY_IDS";
pub const VALIDATION_MISSING_FIELD: &str = "VALIDATION_MISSING_FIELD";

// Chat related
pub const VALIDATION_CHAT_NOT_FOUND: &str = "VALIDATION_CHAT_NOT_FOUND";
pub const VALIDATION_MESSAGE_TOO_LONG: &str = "VALIDATION_MESSAGE_TOO_LONG";
pub const VALIDATION_CHAT_FORBIDDEN: &str = "VALIDATION_CHAT_FORBIDDEN";
pub const VALIDATION_MESSAGE_EMPTY: &str = "VALIDATION_MESSAGE_EMPTY";

// Post deletion
pub const VALIDATION_POST_ALREADY_DELETED: &str = "VALIDATION_POST_ALREADY_DELETED";
pub const VALIDATION_DELETE_REASON_EMPTY: &str = "VALIDATION_DELETE_REASON_EMPTY";
pub const VALIDATION_DELETE_REASON_TOO_LONG: &str = "VALIDATION_DELETE_REASON_TOO_LONG";
pub const VALIDATION_DELETE_NOT_OWNER: &str = "VALIDATION_DELETE_NOT_OWNER";
pub const VALIDATION_DELETE_TARGET_IS_ADMIN: &str = "VALIDATION_DELETE_TARGET_IS_ADMIN";

// Suspension
pub const VALIDATION_USER_ALREADY_SUSPENDED: &str = "VALIDATION_USER_ALREADY_SUSPENDED";
pub const VALIDATION_CANNOT_SUSPEND_SELF: &str = "VALIDATION_CANNOT_SUSPEND_SELF";
pub const VALIDATION_CANNOT_SUSPEND_ADMIN: &str = "VALIDATION_CANNOT_SUSPEND_ADMIN";

// Comment deletion
pub const VALIDATION_COMMENT_ALREADY_DELETED: &str = "VALIDATION_COMMENT_ALREADY_DELETED";
pub const VALIDATION_CANNOT_DELETE_OTHERS_COMMENT: &str = "VALIDATION_CANNOT_DELETE_OTHERS_COMMENT";
pub const VALIDATION_CANNOT_DELETE_ADMIN_COMMENT: &str = "VALIDATION_CANNOT_DELETE_ADMIN_COMMENT";

// Document (real-time collaboration)
pub const VALIDATION_DOC_TITLE_EMPTY: &str = "VALIDATION_DOC_TITLE_EMPTY";
pub const VALIDATION_DOC_TITLE_TOO_LONG: &str = "VALIDATION_DOC_TITLE_TOO_LONG";
pub const VALIDATION_DOC_NOT_FOUND: &str = "VALIDATION_DOC_NOT_FOUND"; // or prefer ApiError::NotFound
pub const VALIDATION_NOT_DOC_VIEWER: &str = "VALIDATION_NOT_DOC_VIEWER";
pub const VALIDATION_NOT_DOC_EDITOR: &str = "VALIDATION_NOT_DOC_EDITOR";
pub const VALIDATION_NOT_DOC_OWNER: &str = "VALIDATION_NOT_DOC_OWNER";
pub const VALIDATION_INVALID_MEMBER_ROLE: &str = "VALIDATION_INVALID_MEMBER_ROLE";
pub const VALIDATION_CANNOT_SHARE_WITH_SELF: &str = "VALIDATION_CANNOT_SHARE_WITH_SELF";
pub const VALIDATION_SNAPSHOT_TOO_LARGE: &str = "VALIDATION_SNAPSHOT_TOO_LARGE";
pub const VALIDATION_NEGATIVE_AFTER_SEQ: &str = "VALIDATION_NEGATIVE_AFTER_SEQ";
pub const VALIDATION_UPDATE_EMPTY: &str = "VALIDATION_UPDATE_EMPTY";
pub const VALIDATION_UPDATE_TOO_LARGE: &str = "VALIDATION_UPDATE_TOO_LARGE";
pub const VALIDATION_SNAPSHOT_EMPTY: &str = "VALIDATION_SNAPSHOT_EMPTY";
